// Generated by Wrangler for Cloudflare Workers type support.
// This file is automatically generated by `wrangler types` and
// committed so that CI and editors have consistent type information.

// NOTE: The actual content will be overwritten by `wrangler types`.
// Do not edit manually.
